# Generated by Django 3.1.3 on 2020-11-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201102_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='champion_imgs'),
        ),
    ]
