# Generated by Django 3.1.3 on 2020-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201102_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='introduction',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
