# Generated by Django 3.1.3 on 2020-11-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201112_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image_bg',
            field=models.ImageField(blank=True, null=True, upload_to='region_imgs'),
        ),
    ]
